config/routes.rb
Rails.application.routes.draw do

  get 'developers/profile'

  get 'developers/edit_profile'

  get 'developers/show_profile'

  get 'jobs/checkAppliedCheckbox'

  get 'jobs/uncheckAppliedCheckbox'

  devise_for :developers

  resources :widgets
  

  get 'frontpage', to: 'welcome/frontpage', controller: 'welcome'

  get 'chat', to: 'welcome/chat', controller: 'welcome'

  root 'welcome#index'

  resources :developers

  get 'side_projects/edit_side_projects'

  resources :side_projects

  devise_scope :developer do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :jobs

  resources :applications

end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_attached_file :profile_image, :s3_protocol => :https
	validates_attachment :profile_image, content_type: { content_type: ["image/jpeg", "image/jpg", "image/png"] }
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
	before_action :authenticate_developer!, only: [:new, :create, :edit, :update, :destroy]


	def index
		@developers = Developer.all
	end

	def new
		@developer = Developer.new
		
	end

	def create
	    @developer = Developer.new(post_params)
	    @developer.CV_counter = 0
	    if @developer.save
	   	  redirect_to "/"
	    else
	      render 'new'
	    end
  	end

	def edit
		@developer = Developer.find(params[:id])
	end

	def update
    	@developer = Developer.find(params[:id])

    	if @developer.update(post_params)
      		redirect_to "/"
    	else
      		render 'edit'
    	end
  	end

  	def profile
    	@developer = Developer.find(current_developer.id)
  	end

  	def edit_profile
		@developer = Developer.find(current_developer.id) 
	end

	def show_profile
		@developer = Developer.find(params[:id])
		@side_projects = SideProject.where(:developer_id => params[:id]).reverse
		@all_posts = Post.all
		@posts = []
		@all_posts.each do |post|
			if post.kind == 'Side Project'
				if SideProject.find(post.side_project).developer_id == params[:id]
					@posts.push(post)
				end
			elsif post.kind == 'Job Application'
				if JobApplication.find(post.application).developer == params[:id]
					@posts.push(post)
				end
			end
		end
	end

	def destroy
		@developer = Developer.find(params[:id])

	    @developer.destroy
	    redirect_to "/"
	end

	

	private

	def post_params
		params.require(:developer).permit(:name, :bio, :personal_website, :profile_image)
	end

end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/edit_profile.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<div style="text-align: center; font-size: 20px; padding-top: 60px; background-color: white;">
	<h1 style="margin:30px;">Edit Details</h1>


	<%= form_for @developer do |d| %>

		</br>
		<p style="color: green;">Your full name.</p>

		<%= d.label :name %></br>
		<%= d.text_field :name, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		<p style="color: green;">Your profile photo.</p>

		<%= d.label :profile_image %></br>
		<% if @developer.profile_image.url != '/profile_images/original/missing.png' %>
			Current Image:<br> <%= image_tag @developer.profile_image.url, :style =>"max-height:200px;" %><br>
			</br><br>
			Change Image:<br><br>
		<% end %>

		<br></br><br></br>
		
		<%= d.file_field :profile_image %>
		<br></br><br>

		<p style="color: green;">Who are you? Describe yourself in a few words. :)</p>

		<%= d.label :bio %></br>
		<%= d.text_area :bio, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>


		<p style="color: green;">Your personal website. It must start with http:// or https://</p>

		<%= d.label :personal_website %></br>
		<%= d.text_field :personal_website, :style => "width: 400px;" %>
		<br></br><br></br>

		
		<br></br><br></br>

		<%= d.submit %>

		<br><br>

		
	<% end %>
</div>

app/views/developers/index.html.erb
<h1 style="text-align: center; margin:30px;">Developers 🤓</h1>
<hr>
<p style="padding-left: 20%; padding-right: 20%; text-align: center;"><b>This is our small community of junior developers.<br>Although we are from completely different parts of the world, we all share and are chasing the same goal.</b></p>

<hr>

<div style="text-align: center; background-color: white;">

	<% @developers.each do |developer| %>
	
	<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">
		<a style="color:black; text-decoration: none;" href="/developers/show_profile?id=<%= developer.id %>" ><img id="card-img-top" src="<%= developer.profile_image.url %>" style="border-radius: 50%; height:75px; margin:10px;" /><b><%= developer.name %> </b>- <%= developer.bio %></a>
		
	</div>
	<% end %>

</div>

app/views/developers/new.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<div style="text-align: center; font-size: 20px; padding-top: 60px; background-color: white;">
	<h1 style="margin:30px;">Edit Details</h1>


	<%= form_for @developer do |d| %>

		</br>
		<p style="color: green;">Your full name.</p>

		<%= d.label :name %></br>
		<%= d.text_field :name, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		<p style="color: green;">Your profile photo.</p>

		<%= d.label :profile_image %></br>
		<%= d.file_field :profile_image %>
		<br></br><br></br>

		<p style="color: green;">Who are you? Describe yourself in a few words. :)</p>

		<%= d.label :bio %></br>
		<%= d.text_area :bio, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>


		<p style="color: green;">Your personal website. It must start with http:// or https://</p>

		<%= d.label :personal_website %></br>
		<%= d.text_field :personal_website, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		
		<br></br><br></br>

		<%= d.submit %>

		<br><br>
		
	<% end %>
</div>

app/views/developers/profile.html.erb
<div style="height:1000px; text-align: center; padding-top: 50px; background-image: linear-gradient(to bottom, #fff 0%, #cfd9df 30%);">
    <% if @developer.name != nil %>
	   <p style="font-size: 25px; padding:10px;"><b>Welcome back, <%= @developer.name.strip.split(" ")[0] %>!<br></b></p>
    <% else %>
        <p style="font-size: 25px; padding:10px;"><b>Welcome back!<br></b></p>
    <% end %>
	<p>Please select one of the following actions:</p>
	<div class="btn btn-primary my_btn" style="background-color: #476987; text-align: center; font-size: 18px; margin-bottom: 25px; margin-top: 25px; border: none;">
    	<a href="/developers/edit_profile" style="color:white; text-decoration: none; padding-left: 30px; padding-right: 30px; padding-top: 15px;">Edit My Details</a>
    </div>

    <br>
    <div class="btn btn-primary my_btn" style="background-color: #476987; text-align: center; font-size: 18px; margin-bottom: 25px; margin-top: 25px; border: none;">
        <a href="/side_projects/new" style="color:white; text-decoration: none; padding-left: 30px; padding-right: 30px; padding-top: 15px;">Add Side Project</a>
    </div>

    <br>
    <div class="btn btn-primary my_btn" style="background-color: #476987; text-align: center; font-size: 18px; margin-bottom: 25px; margin-top: 25px; border: none;">
        <a href="/side_projects/edit_side_projects" style="color:white; text-decoration: none; padding-left: 30px; padding-right: 30px; padding-top: 15px;">Edit Side Projects</a>
    </div>

    
    
    <br>
    <%= link_to "Change password", edit_developer_registration_path, :class => "btn btn-primary my_btn", :style => "background-color: #476987; text-align: center; font-size: 18px; margin-bottom: 25px; margin-top: 25px; border: none; color:white; padding-left:30px; padding-right:30px;", method: :delete, data: {confirm: ""} %>
    <br>
    <%= button_to "Log out", "/developers/sign_out/", :class => "btn", :style => "background-color: #D85537; text-align: center; font-size: 18px; margin-bottom: 25px; margin-top: 25px; border: none; color:white; padding-left:30px; padding-right:30px;", method: :delete, data: {confirm: ""} %>




</div>

app/views/developers/show_profile.html.erb
<div style="height:1000px; text-align: center; margin-top: 50px;">

<div style="">
	<div class="col col-lg-6">
		<img id="card-img-top" src="<%= @developer.profile_image.url %>" style="border-radius: 50%; height:150px; margin:30px;" />
		<h1 style="margin: 0px;"><%= @developer.name %></h1>
		<p style="margin: 20px;"><%= @developer.bio %></p>
		<p style=""><span class="glyphicon glyphicon-fire"></span> <b><%= @developer.CV_counter %> applications this month.</b></p>
		<p style=""><span class="glyphicon glyphicon-fire"></span> <b><%= @developer.side_project_counter %> side projects this month.</b></p>
		<p style=""><span class="glyphicon glyphicon-fire"></span> <b>Total: <%= @developer.points %></b></p>
		<a target="_blank" class= "btn" style="margin:20px; background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); padding: 10px; color: black; border: none;" href="<%= @developer.personal_website %>"><b>Personal website/blog.</b></a><br>
	</div>
	<div class="col col-lg-6" style="text-align: center; background-color: white;">
		<h3 style="padding-bottom: 30px;">Recent Activity</h3>
		<% @posts.each do |post| %>
			<% if post.kind == 'Job Application' %>
				<a href="/developers/show_profile?id=<%= Developer.find(JobApplication.find(post.application).developer).id %>"><img id="card-img-top" src="<%= Developer.find(JobApplication.find(post.application).developer).profile_image.url %>" style="border-radius: 50%; height:50px; margin-bottom:10px;" /></a>
				<p style="margin: 0px; margin-top: 0px;"><b><%= Developer.find(JobApplication.find(post.application).developer).name %> just applied for a job: <%= Job.find(JobApplication.find(post.application).job).url %> (+1 points)</b></p>
			<% elsif post.kind == 'Side Project' %>
				<a href="/developers/show_profile?id=<%= Developer.find(SideProject.find(post.side_project).developer_id).id %>"><img id="card-img-top" src="<%= Developer.find(SideProject.find(post.side_project).developer_id).profile_image.url %>" style="border-radius: 50%; height:50px; margin-bottom:10px;" /></a>
					<p style="margin: 0px; margin-top: 0px;"><b><%= Developer.find(SideProject.find(post.side_project).developer_id).name %> just created a new side project: <%= SideProject.find(post.side_project).name %> (+25 points)</b></p>
			<% end %>
		<% end %>


	</div>
</div>

<div class="col col-lg-12" style="margin-top: 50px;">
	<hr>
	<h1><%= @developer.name %>'s Side Projects</h1>
	<hr>

	<% @side_projects.each do |sp| %>
		<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">
			<a style="color:black; text-decoration: none;" href="/side_projects/<%= sp.id %>" ><img id="card-img-top" src="<%= sp.image.url %>" style="height:50px; margin:20px;" /><b><%= sp.name %> </b>- <%= sp.description %></a>
			
		</div>
	<% end %>

</div>