config/routes.rb
Rails.application.routes.draw do

  get 'developers/profile'

  get 'developers/edit_profile'

  get 'developers/show_profile'

  get 'jobs/checkAppliedCheckbox'

  get 'jobs/uncheckAppliedCheckbox'

  devise_for :developers

  resources :widgets
  

  get 'frontpage', to: 'welcome/frontpage', controller: 'welcome'

  get 'chat', to: 'welcome/chat', controller: 'welcome'

  root 'welcome#index'

  resources :developers

  get 'side_projects/edit_side_projects'

  resources :side_projects

  devise_scope :developer do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :jobs

  resources :applications

end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :authenticate_developer!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@jobs = Job.all.reverse
	end

	def new
		@job = Job.new
	end

	def create
	    @job = Job.new(post_params)
	    @job.creator = current_developer.id
	    
	    if @job.save
	   	  	redirect_to "/frontpage"
	    else
	      render 'new'
	    end
  	end

	def edit
		@job = Job.find(params[:id])
		if current_developer.id != @job.creator
			redirect_to "/frontpage"
		end
	end

	def update
    	@job = Job.find(params[:id])

    	if @job.update(post_params)
      		redirect_to "/"
    	else
      		render 'edit'
    	end
  	end

	def destroy
		@job = Job.find(params[:id])

		@applications = JobApplication.where(:job => @job.id)
		if @applications.length == 0
			@job.destroy
		end
	    
	    redirect_to "/"
	end

	def checkAppliedCheckbox
		# Create a new application and save it
		@application = JobApplication.new
		@application.job = params[:job]
	    @application.developer = current_developer.id
	    @application.save

	    @post = Post.new
	    @post.kind = 'Job Application'
	    @post.application = @application.id
	    @post.save

	    # Update his/her CV counter and save
	    current_developer.CV_counter = current_developer.CV_counter + 1
	    current_developer.points = current_developer.points + 1
	    	
    	current_developer.save

	end

	def uncheckAppliedCheckbox
		# Find the job application and post, delete them
		@application = JobApplication.where(:job => params[:job], :developer => current_developer.id).first
	    @post = Post.where(:kind => 'Job Application', :application => @application.id).first
	    
	    puts @post

	    @application.destroy
	    @post.destroy

	    # Update his/her CV counter and save it
	    current_developer.CV_counter = current_developer.CV_counter - 1
	    current_developer.points = current_developer.points - 1
	    	
    	current_developer.save

	end

	

	private

	def post_params
		params.require(:job).permit(:url, :title, :company)
	end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<div style="text-align: center; font-size: 20px; padding-top: 60px; background-color: white;">
	<h1 style="margin:30px;">Edit Job</h1>


	<%= form_for @job do |ap| %>

		</br>
		<p style="color: green;">Title. ex 'Junior Software Engineer'</p>

		<%= ap.label :title %> </br>
		<%= ap.text_field :title, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		<p style="color: green;">Company. ex 'ProductHunt'</p>
		<%= ap.label :company %> </br>
		<%= ap.text_field :company, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>


		<p style="color: green;">Url. Must start with http:// or https://</p>
		<%= ap.label :url %> </br>
		<%= ap.text_field :url, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		
		<br></br><br></br>

		

		<%= ap.submit %>

		<br><br><br><br><br><br>

		<%= link_to "Delete Job Post", @job, :method => :delete, :style => 'font-size: 11px; color:red;' %>

		
	<% end %>
</div>

app/views/jobs/index.html.erb
<h1 style="text-align: center; margin:30px;">Job Board 🕵🏼</h1>
<hr>
<p style="text-align: center; padding-right: 10%; padding-left: 10%;"><b>This is a crowdsourced job board, meaning that we post the job applications we apply for, in order to help out others as well.</b></p>


<hr>


<div style="text-align: center; margin:20px;">
	<a href="/jobs/new" class="btn btn-success" style="color:white;">Add a new job!</a>
</div>

<hr>

<div style="text-align: center;">
	<a id="all_btn" class="btn" style="background-color: grey; color:white; margin-bottom: 20px;">All</a>
	<a id="applied_btn" class="btn" style="background-color: #191919; color:white; margin-bottom: 20px;">Applied</a>
	<a id="have_not_applied_btn" class="btn" style="background-color: #191919; color:white; margin-bottom: 20px;">Have not Applied</a>
</div>

<div id="all">
	<% @jobs.each do |job| %>
		<% if developer_signed_in? %>
			<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">
				<% if developer_signed_in? %>
					<% if current_developer.id == job.creator %>
						<a style="padding-left: 10px;" href="/jobs/<%= job.id %>/edit">Edit</a>
					<% end %>
				<% end %>

				
				<% if !JobApplication.where(:job => job.id, :developer => current_developer.id).empty? %>
					<a style="padding:10px; color:black; text-decoration: none;" target="_blank" href="<%= job.url %>" ><b><%= job.title %> at <%= job.company %><span style="margin: 15px; background-color: grey; color: white;" class="btn">Applied</span></b></a>
					<input type="checkbox" value="<%= job.id %>" onchange="toggleCheckbox(this)" checked><span style="font-size: 14px;"> I Applied for this job</span>
				<% else %>
					<a style="padding:10px; color:black; text-decoration: none;" target="_blank" href="<%= job.url %>" ><b><%= job.title %> at <%= job.company %><span style="margin: 15px;" class="btn btn-info">Apply</span></b></a>
					<input type="checkbox" value="<%= job.id %>" onchange="toggleCheckbox(this)"><span style="font-size: 14px;"> I Applied for this job</span>

				<% end %>
			</div>

		<% else %>
			<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">
				<a style="padding:10px; color:black; text-decoration: none;" target="_blank" href="<%= job.url %>" ><b><%= job.title %> at <%= job.company %><span style="margin: 15px;" class="btn btn-info">Apply</span></b></a>
			</div>

		<% end %>
	<% end %>
</div>

<div id="have_not_applied" style="display: none;">
	<% if developer_signed_in? %>
		<% @jobs.each do |job| %>
			<% if JobApplication.where({ job: job.id, developer: current_developer.id }).empty? %>
				<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">
					<% if developer_signed_in? %>
						<% if current_developer.id == job.creator %>
							<a style="padding-left: 10px;" href="/jobs/<%= job.id %>/edit">Edit</a>
						<% end %>
					<% end %>

					<a style="padding:10px; color:black; text-decoration: none;" target="_blank" href="<%= job.url %>" ><b><%= job.title %> at <%= job.company %><span style="margin: 15px;" class="btn btn-info">Apply</span></b></a>
					<input type="checkbox" value="<%= job.id %>" onchange="toggleCheckbox(this)"><span style="font-size: 14px;"> I Applied for this job</span>

					
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>

<div id="have_applied" style="display: none;">
	<% @jobs.each do |job| %>
		<% if developer_signed_in? %>
			<% if !JobApplication.where({ job: job.id, developer: current_developer.id }).empty? %>
				<div class="col col-lg-12" style="background-image: linear-gradient(to top, #a8edea 10%, #fed6e3 120%); text-align: center; margin-left: auto; margin-right: auto; display: block; align-self: center; margin-bottom: 20px;">

					<% if developer_signed_in? %>
						<% if current_developer.id == job.creator %>
							<a style="padding-left: 10px;" href="/jobs/<%= job.id %>/edit">Edit</a>
						<% end %>
					<% end %>
					<a style="padding:10px; color:black; text-decoration: none;" target="_blank" href="<%= job.url %>" ><b><%= job.title %> at <%= job.company %><span style="margin: 15px; background-color: grey; color: white;" class="btn">Applied</span></b></a>
					
					<input type="checkbox" value="<%= job.id %>" onchange="toggleCheckbox(this)" checked><span style="font-size: 14px;"> I Applied for this job</span>

					
					
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/jobs/new.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<div style="text-align: center; font-size: 20px; padding-top: 60px; background-color: white;">
	<h1 style="margin:30px;">New Job</h1>


	<%= form_for @job do |ap| %>

		</br>
		<p style="color: green;">Title. ex 'Junior Software Engineer'</p>

		<%= ap.label :title %> </br>
		<%= ap.text_field :title, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		<p style="color: green;">Company. ex 'ProductHunt'</p>
		<%= ap.label :company %> </br>
		<%= ap.text_field :company, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>


		<p style="color: green;">Url. Must start with http:// or https://</p>
		<%= ap.label :url %> </br>
		<%= ap.text_field :url, :required => true, :style => "width: 400px;" %>
		<br></br><br></br>

		
		<br></br><br></br>

		

		<%= ap.submit %>

		<br><br>
		
	<% end %>
</div>